main: tech.secretgarden.stash.Stash
name: Stash
author: ChuckLingBao
version: 1.3.1
api-version: 1.18
commands:
  stash:
    description: This is where your rewards are.
  stashsf:
    description: This will give Slimefun items.
  stashkey:
    description: This will give keys.