main: tech.secretgarden.stash.Stash
name: Stash
author: ChuckLingBao
version: '2.0.0'
api-version: 1.19
commands:
  stash:
    description: This is where your rewards are.
  stashsf:
    description: This will give Slimefun items.
  stashkey:
    description: This will give keys.
  verify:
    description: Verifies your MC account with www.SecretGarden.tech
  randomspawner:
    description: Gives a random spawner to a player.