main: tech.secretgarden.stash.Main
name: Stash
version: 1.0
api-version: 1.17
commands:
  stash:
    description: This is where your rewards are.
  stashsf:
    description: This will give Slimefun items.