main: tech.secretgarden.stash.Main
name: Stash
author: ChuckLingBao
version: 1.2.0
api-version: 1.17
commands:
  stash:
    description: This is where your rewards are.
  stashsf:
    description: This will give Slimefun items.
  stashkey:
    description: This will give keys.